version: 2

jobs:
  build:
    docker:
      - image: rust:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:12
        environment:
          POSTGRES_USER: streaker
          POSTGRES_DB: streaker
          POSTGRES_PASSWORD: streaker
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run: 
          name: Migrate database
          environment:
            DATABASE_URL: "jdbc:postgresql://localhost/streaker?user=streaker&password=streaker"
          command: cd backend && cargo run --bin migrate
      - run:
          name: Build all targets
          environment:
            DATABASE_URL: "jdbc:postgresql://localhost/streaker?user=streaker&password="
          command: cargo build --release
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          environment:
            TESTBASE_URL: "jdbc:postgresql://localhost/streaker?user=streaker&password="
          command: cargo test --release
