apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaker
  labels:
    app.kubernetes.io/name: streaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: streaker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: streaker
    spec:
      containers:
        - name: streaker
          image: "${IMAGE}"
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: "${STREAKER_DATABASE_URL}"
            - name: STREAKER_CORS_ORIGIN
              value: "${CORS_ORIGIN}"
            - name: PORT
              value: "8080"
            - name: RUST_LOG
              value: "debug"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
          readinessProbe:
            httpGet:
              path: /healthy
              port: http
          resources:
            {}
